// /*
// Copyright The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
// Source: /Volumes/git/opensource/forks/cloud-provider-azure/pkg/azureclients/v2/resourcegraph/interface.go
//
// Generated by this command:
//
//	mockgen -copyright_file=/Volumes/git/opensource/forks/cloud-provider-azure/hack/boilerplate/boilerplate.generatego.txt -source=/Volumes/git/opensource/forks/cloud-provider-azure/pkg/azureclients/v2/resourcegraph/interface.go -package=mockresourcegraph Interface
//

// Package mockresourcegraph is a generated GoMock package.
package mockresourcegraph

import (
	context "context"
	reflect "reflect"

	resourcegraph "github.com/Azure/azure-sdk-for-go/services/resourcegraph/mgmt/2021-03-01/resourcegraph"
	gomock "go.uber.org/mock/gomock"
	retry "sigs.k8s.io/cloud-provider-azure/pkg/retry"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// SendQuery mocks base method.
func (m *MockInterface) SendQuery(ctx context.Context, subscriptionID, query string) (resourcegraph.QueryResponse, *retry.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendQuery", ctx, subscriptionID, query)
	ret0, _ := ret[0].(resourcegraph.QueryResponse)
	ret1, _ := ret[1].(*retry.Error)
	return ret0, ret1
}

// SendQuery indicates an expected call of SendQuery.
func (mr *MockInterfaceMockRecorder) SendQuery(ctx, subscriptionID, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendQuery", reflect.TypeOf((*MockInterface)(nil).SendQuery), ctx, subscriptionID, query)
}
